---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "argocd"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

  project: default
  sources:

    - repoURL: "https://argoproj.github.io/argo-helm"
      chart: "argo-cd"
      targetRevision: 7.7.16
      helm:
        valueFiles:
          - $values/values.yaml
      
    - repoURL: 'https://github.com/nflenz/argocd'
      targetRevision: main
      ref: values

    - repoURL: 'https://github.com/nflenz/argocd/'
      path: 'manifests'
      targetRevision: main
