---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "grafana"
  project: default
  sources:

    - repoURL: "https://grafana.github.io/helm-charts"
      chart: "grafana"
      targetRevision: 8.8.3
      helm:
        valueFiles:
          - $values/values.yaml
      
    - repoURL: 'https://github.com/nflenz/grafana'
      targetRevision: main
      ref: values
