---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "prometheus"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
  project: default
  sources:

    - repoURL: "https://prometheus-community.github.io/helm-charts"
      chart: "prometheus"
      targetRevision: 26.1.0
      helm:
        valueFiles:
          - $values/values.yaml
      
    - repoURL: 'https://github.com/nflenz/prometheus'
      targetRevision: main
      ref: values
